name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          sudo apt install -y zip unzip openjdk-17-jdk
          sudo apt install -y libncurses5 libstdc++6
          virtualenv venv
          source venv/bin/activate
          pip install buildozer
          buildozer init
          sed -i 's/.*title.*/title = To-Do List/' buildozer.spec
          sed -i 's/.*source.include_exts.*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          sed -i 's/.*requirements.*/requirements = python3,kivy,kivymd/' buildozer.spec
          sed -i 's/.*android.permissions.*/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/.*android.minapi.*/android.minapi = 21/' buildozer.spec
          sed -i 's/.*android.sdk.*/# android.sdk =/' buildozer.spec
          sed -i 's/.*package.domain.*/package.domain = org.bhaigpt.todo/' buildozer.spec
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ToDoList.apk
          path: bin/*.apk
